<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>OpenTabletDriver.Desktop</AssemblyName>
    <RootNamespace>OpenTabletDriver.Desktop</RootNamespace>
    <Version>0.6.7</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <NoWarn>VSTHRD100;VSTHRD101;VSTHRD110;VSTHRD200</NoWarn>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <PackageLicenseExpression>LGPL-3.0-or-later</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenTabletDriver" Version="[0.6.7]" />
    <PackageReference Include="OpenTabletDriver.Native" Version="[0.6.7]" />
    <PackageReference Include="OpenTabletDriver.Configurations" Version="[0.6.7]" />
    <PackageReference Include="JetBrains.Annotations" Version="[2025.2.4]" />
    <PackageReference Include="Octokit" Version="[14.0.0]" />
    <PackageReference Include="SharpZipLib" Version="[1.4.2]" />
    <PackageReference Include="StreamJsonRpc" Version="[2.22.23]" />
    <PackageReference Include="System.CommandLine" Version="[2.0.1]" />
    <PackageReference Include="WaylandNET" Version="[0.2.0]" />
  </ItemGroup>
</Project>
