#!/usr/bin/env python3
"""Regenerate permissions from the pinned database, like upstream generate-rules.sh.

Reference: OpenTabletDriver/OpenTabletDriver@736003ed, generate-rules.sh.
Include both endpoint roles and scope USB access to concrete VID/PID pairs.
"""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[2]
pairs = {}
for path in sorted((root / "crates/otd-core/tablets").rglob("*.json")):
    config = json.loads(path.read_text(encoding="utf-8-sig"))
    for role in ("DigitizerIdentifiers", "AuxiliaryDeviceIdentifiers"):
        for identifier in config.get(role, []) or []:
            vendor, product = identifier.get("VendorID"), identifier.get("ProductID")
            if isinstance(vendor, int) and isinstance(product, int) and 0 <= vendor <= 65535 and 0 <= product <= 65535:
                pairs.setdefault((vendor, product), set()).add(config["Name"])
lines = [
    "# OpenTabletDriver Rust permissions. Generated by generate-rules.py.",
    "# Based on upstream generate-rules.sh at 736003ed72c8bbb28033b039d5a0bb76c344145c.",
    "# Keep this filename before 73-seat-late.rules so uaccess ACLs are applied.",
    'KERNEL=="uinput", SUBSYSTEM=="misc", OPTIONS+="static_node=uinput", TAG+="uaccess"',
    'SUBSYSTEM=="input", ATTRS{name}=="OpenTabletDriver Virtual*", ENV{LIBINPUT_DEVICE_GROUP}="OpenTabletDriver"',
    "",
]
for (vendor, product), names in sorted(pairs.items()):
    lines.append("# " + ", ".join(sorted(names)))
    match = f'ATTRS{{idVendor}}=="{vendor:04x}", ATTRS{{idProduct}}=="{product:04x}"'
    lines.append(f'KERNEL=="hidraw*", {match}, TAG+="uaccess"')
    lines.append(f'SUBSYSTEM=="usb", {match}, TAG+="uaccess"')
(root / "packaging/linux/70-opentabletdriver-rust.rules").write_text("\n".join(lines) + "\n", encoding="utf-8")
