<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RollForward>LatestMajor</RollForward>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <License>LGPL-3.0-only</License>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenTabletDriver.Plugin" Version="0.6.7" />
  </ItemGroup>
</Project>
