<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Project Properties">
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>OpenTabletDriver.UX.Gtk</AssemblyName>
    <RootNamespace>OpenTabletDriver.UX.Gtk</RootNamespace>
    <Version>0.6.7</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <PackageLicenseExpression>LGPL-3.0-or-later</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup Label="NuGet Packages">
    <PackageReference Include="Eto.Platform.Gtk" Version="2.5.11" />
  </ItemGroup>

  <ItemGroup Label="Project References">
    <ProjectReference Include="..\UpstreamUX\OpenTabletDriver.UX.csproj" />
  </ItemGroup>

</Project>
